app: Fix errors and warnings when building with R8
> Task :app:compileOptimizedDebugKotlin
w: file:///home/flopster101/Escritorio/drdsnd_alt_exp/repo/app/src/main/java/com/flopster101/siliconplayer/ui/screens/PlayerVisualization.kt:202:24 'val defaultDisplay: Display!' is deprecated. Deprecated in Java.

> Task :app:minifyOptimizedDebugWithR8
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/flopster101/Escritorio/drdsnd_alt_exp/repo/app/build/outputs/mapping/optimizedDebug/missing_rules.txt.
ERROR: R8: Missing class java.rmi.UnmarshalException (referenced from: void com.rapid7.client.dcerpc.messages.RequestResponse.unmarshal(com.rapid7.client.dcerpc.io.PacketInput) and 4 other contexts)
Missing class javax.annotation.Nullable (referenced from: void com.google.common.io.CountingInputStream.<init>(java.io.InputStream) and 1 other context)
Missing class javax.el.BeanELResolver (referenced from: void net.engio.mbassy.dispatch.el.StandardELResolutionContext.<init>(java.lang.Object))
Missing class javax.el.ELContext (referenced from: boolean net.engio.mbassy.dispatch.el.ElFilter.evalExpression(java.lang.String, net.engio.mbassy.dispatch.el.StandardELResolutionContext, net.engio.mbassy.subscription.SubscriptionContext, java.lang.Object) and 2 other contexts)
Missing class javax.el.ELResolver (referenced from: javax.el.ELResolver net.engio.mbassy.dispatch.el.StandardELResolutionContext.resolver)
Missing class javax.el.ExpressionFactory (referenced from: javax.el.ExpressionFactory net.engio.mbassy.dispatch.el.ElFilter$ExpressionFactoryHolder.ELFactory and 5 other contexts)
Missing class javax.el.FunctionMapper (referenced from: javax.el.FunctionMapper net.engio.mbassy.dispatch.el.StandardELResolutionContext.functionMapper and 2 other contexts)
Missing class javax.el.ValueExpression (referenced from: javax.el.ValueExpression net.engio.mbassy.dispatch.el.StandardELResolutionContext$MsgMapper.msgExpression and 2 other contexts)
Missing class javax.el.VariableMapper (referenced from: javax.el.VariableMapper net.engio.mbassy.dispatch.el.StandardELResolutionContext.variableMapper and 2 other contexts)
Missing class org.ietf.jgss.GSSContext (referenced from: org.ietf.jgss.GSSContext com.hierynomus.smbj.auth.SpnegoAuthenticator.gssContext and 2 other contexts)
Missing class org.ietf.jgss.GSSCredential (referenced from: org.ietf.jgss.GSSCredential com.hierynomus.smbj.auth.GSSAuthenticationContext.getCreds() and 1 other context)
Missing class org.ietf.jgss.GSSException (referenced from: com.hierynomus.smbj.auth.AuthenticateResponse com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(com.hierynomus.smbj.auth.GSSAuthenticationContext, byte[], com.hierynomus.smbj.connection.ConnectionContext))
Missing class org.ietf.jgss.GSSManager (referenced from: com.hierynomus.smbj.auth.AuthenticateResponse com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(com.hierynomus.smbj.auth.GSSAuthenticationContext, byte[], com.hierynomus.smbj.connection.ConnectionContext))
Missing class org.ietf.jgss.GSSName (referenced from: com.hierynomus.smbj.auth.AuthenticateResponse com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(com.hierynomus.smbj.auth.GSSAuthenticationContext, byte[], com.hierynomus.smbj.connection.ConnectionContext))
Missing class org.ietf.jgss.Oid (referenced from: com.hierynomus.smbj.auth.AuthenticateResponse com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(com.hierynomus.smbj.auth.GSSAuthenticationContext, byte[], com.hierynomus.smbj.connection.ConnectionContext))

> Task :app:minifyOptimizedDebugWithR8 FAILED

FAILURE: Build failed with an exception.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>