github: Don't force --depth=1
Due to whatever is going on here:

Error: error: Server does not allow request for unadvertised object 57fe25977353bdfb4c2baa4d018538a73fbe3a19
Error: fatal: Fetched in submodule path 'external/ffmpeg', but it did not contain 57fe25977353bdfb4c2baa4d018538a73fbe3a19. Direct fetching of that commit failed.
Error: The process '/usr/bin/git' failed with exit code 128

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>